## Copyright (c) 2022, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Create compute instance and an Autonomous Transaction Processing (ATP) database in Oracle Cloud Infrastructure"
    stackDescription: "This code will help you deploy a compute instance and an Autonomous Transaction Processing (ATP) database in Oracle Cloud Infrastructure."
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid
      - region   
      - release  
      - availability_domain_number

    - title: Required Configuration
      visible: true  
      variables:
      - compartment_ocid
      - availability_domain_name 
      - autonomous_database_admin_password
      - autonomous_database_private_endpoint
      - show_advanced  

    - title: Compute Optional Configuration
      visible: 
          and:
            - show_advanced
      variables:      
      - ssh_public_key
      - instance_os
      - linux_os_version
      - instance_shape
      - instance_shape_flex_ocpus
      - instance_shape_flex_memory
      - volume_display_name
      - volume_size_in_gbs
      - volume_count
      - volume_attachment_type

    - title: Autonomous Database Optional Configuration
      visible: 
          and:
            - show_advanced
      variables:   
      - autonomous_private_endpoint_label  
      - autonomous_database_cpu_core_count
      - autonomous_database_db_version
      - autonomous_database_db_name
      - autonomous_database_display_name
      - autonomous_database_is_auto_scaling_enabled
      - autonomous_database_data_storage_size_in_tbs
      - autonomous_database_db_workload
      - autonomous_database_license_model
      - autonomous_database_data_safe_status
    
    variables:

      show_advanced:
        type: boolean
        title: "Show advanced options?"
        description: "Shows advanced options."
        visible: true
        default: false

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Choose Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Choose Region where you want to deploy the resources defined by this stack."

      autonomous_database_admin_password:
        type: password
        required: true
        title: "Autonomous Database Admin password"
        description: "Type password for admin user in Autonomous Database."
        minLength: 12
        maxLength: 30
        pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

      autonomous_database_private_endpoint:
        type: boolean
        visible: true
        default: true
        required: false
        title: "Autonomous Database Private Endpoint"
        description: "Check the box to deploy Autonomous Database with Private Endpoint."

      availability_domain_name:
        type: oci:identity:availabilitydomain:name
        required: true
        visibile: true
        title: "Availability Domain to be chosen"
        description: "Choose Availability Domain where your infrastructure will be deployed."
        dependsOn:
          regionName: ${region}
          compartmentId: ${compartment_ocid}

      # Optional Configuration

      ssh_public_key:
        type: oci:core:ssh:publickey
        title: "Public SSH Key"
        description: "Choose public SSH Key to be uploaded into compute instances."
        required: false

      instance_os: 
        type: enum
        required: false
        default: "Oracle Linux"
        title: "Operating system"
        description: "Choose Operating System for your compute instances."
        enum:
          - "Oracle Linux"

      linux_os_version:
        type: enum
        required: false
        default: "8"
        title: "Operating system version"
        description: "Choose Operating System version for your compute instances."
        enum:
          - "8"
          - "7.9"

      instance_shape:
        type: oci:core:instanceshape:name
        required: false
        default: "VM.Standard.E4.Flex"
        title: "Instance Shape"
        description: "Choose instance shape for your compute instances."
        dependsOn:
          compartmentId: ${compartment_ocid}

      instance_shape_flex_ocpus:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 1
        title: "Flex Shape OCPUs"
        description: "Choose number of OCPUs for Flex Shape."
        visible:
          and:
            - or:
              - eq:
                - instance_shape 
                - "VM.Standard.E3.Flex"
              - eq:
                - instance_shape 
                - "VM.Standard.E4.Flex"

      instance_shape_flex_memory:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 10
        title: "Flex Shape Memory (GB)"
        description: "Choose number GB for Flex Shape Memory."
        visible:
          and:
            - or:
              - eq:
                - instance_shape 
                - "VM.Standard.E3.Flex"
              - eq:
                - instance_shape
                - "VM.Standard.E4.Flex"

      volume_display_name:
        type: string
        required: false
        default: "AppVolume1"
        title: "Instance Volume Display Name"
        description: "Type instance volume display Name."

      volume_size_in_gbs:
        type: number
        required: false
        default: 100
        minimum: 50
        maximum: 32000
        multipleOf: 1
        title: "Instance Volume Size (GBs)"
        description: "Choose instance volume size in gigabytes (min 50GB, Max 32TB)."

      volume_count:
        type: number
        required: false
        default: 1
        minimum: 1
        maximum: 32
        multipleOf: 1
        title: "Instance Volume Count"
        description: "Choose instance volume count (min 1, max 32)" 

      volume_attachment_type:
        type: enum
        required: false
        default: "paravirtualized"
        title: "Instance Volume Attachment Type"
        description: "Choose instance volume attachment type."
        enum:
          - "paravirtualized"
      
      autonomous_database_cpu_core_count:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 4
        title: "Autonomous database CPU core count"
        description: "Choose autonomous database CPU core count (min 1, max 128)."

      autonomous_database_db_name:
        type: string
        required: false
        default: "migatp"
        title: "Autonomous database DB Name"
        description: "Type autonomous database DB Name."

      autonomous_database_db_version:
        type: enum
        required: false
        default: "19c"
        title: "Autonomous Database Version"
        description: "Choose Autonomous Database Version."
        enum:
          - "19c"

      autonomous_database_display_name:
        type: string
        required: false
        default: "MigratedATP"
        title: "Autonomous database display name"
        description: "Type autonomous database display name."

      autonomous_private_endpoint_label:
        type: string
        required: false
        visible: 
          and:
            - autonomous_database_private_endpoint
        default: "migatppe"
        title: "Autonomous Database Private Endpoint Label"
        description: "Choose Autonomous Database Private Endpoint Label"

      autonomous_database_is_auto_scaling_enabled:
        type: boolean
        required: false
        default: false
        title: "Autonomous database auto-scaling enabled."
        description: "Choose if autonomous database auto-scaling will be enabled."

      autonomous_database_data_storage_size_in_tbs:
        type: number
        required: false
        minimum: 1
        maximum: 128
        multipleOf: 1
        default: 1
        title: "Autonomous database Data Storage Size"
        description: "Choose autonomous database data storage size in terabytes (min 1TB, max 128TB)."  

      autonomous_database_db_workload:
        type: enum
        required: false
        default: "OLTP"
        title: "Autonomous database DB workload"
        description: "Choose autonomous database DB workload type."      
        enum:
          - "OLTP"

      autonomous_database_license_model:
        type: enum
        required: false
        default: "BRING_YOUR_OWN_LICENSE"
        title: "Autonomous database License Model"
        description: "Choose autonomous database license model." 
        enum:
          - "LICENSE_INCLUDED"
          - "BRING_YOUR_OWN_LICENSE"

      autonomous_database_data_safe_status:
        type: enum
        required: false
        default: "NOT_REGISTERED"
        title: "Autonomous database DataSafe Status"
        description: "Choose autonomous database DataSafe status" 
        enum:
          - "NOT_REGISTERED"
          
      release:
        type: string
        required: false
        visible: false
        title: "Reference Architecture Release (OCI Architecture Center)"

    outputs:
      generated_ssh_private_key:
        title: "Generated SSH Private Key"
        displayText: "Generated SSH Private Key"
        type: string
        visible: true
